apiVersion: v1
kind: Secret
metadata:
  name: gogs-secret
  namespace: gogs

type: Opaque

stringData:
  DB_TYPE: postgres
  DB_HOST: postgres.postgres.svc.cluster.local:5432
  DB_NAME: gogs
  DB_USER: gogs
  DB_PASSWORD: gogs123
  SECRET_KEY: change-this-to-a-long-random-secret
