apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs
  namespace: gogs

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gogs

  template:
    metadata:
      labels:
        app: gogs

    spec:
      containers:
        - name: gogs
          image: gogs/gogs:0.14

          ports:
            - containerPort: 3000
            - containerPort: 22

          env:
            - name: DB_TYPE
              valueFrom:
                secretKeyRef:
                  name: gogs-secret
                  key: DB_TYPE

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: gogs-secret
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gogs-secret
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gogs-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gogs-secret
                  key: DB_PASSWORD

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gogs-secret
                  key: SECRET_KEY

          volumeMounts:
            - name: gogs-data
              mountPath: /data

      volumes:
        - name: gogs-data
          emptyDir: {}
